### ISSUE TITLE
按照要求安装后启动报错

### ISSUE THREAD

**Issue by 372572571** [tmtbe/SwooleDistributed#16]
Press Ctrl-C to quit. Start success.
ERR Client sent AUTH, but no password is set
PHP Fatal error:  Uncaught Server\CoreBase\SwooleException: ERR Client sent AUTH, but no password is set in /home/lyl/SwooleDistributed/src/Server/Asyn/Redis/RedisAsynPool.php:414
Stack trace:
#0 /home/lyl/SwooleDistributed/src/Server/SwooleDistributedServer.php(147): Server\Asyn\Redis\RedisAsynPool->getSync()
#1 /home/lyl/SwooleDistributed/src/Server/SwooleServer.php(569): Server\SwooleDistributedServer->start()
#2 /home/lyl/SwooleDistributed/src/Server/SwooleServer.php(263): Server\SwooleServer::startSwooles()
#3 /home/lyl/SwooleDistributed/bin/start_swoole_server.php(11): Server\SwooleServer::run()
#4 {main}
  thrown in /home/lyl/SwooleDistributed/src/Server/Asyn/Redis/RedisAsynPool.php on line 414
服务器发生崩溃事件
WORKER EXIT UNEXPECTED Uncaught Server\CoreBase\SwooleException: ERR Client sent AUTH, but no password is set in /home/lyl/SwooleDistributed/src/Server/Asyn/Redis/RedisAsynPool.php:414
Stack trace:
#0 /home/lyl/SwooleDistributed/src/Server/SwooleDistributedServer.php(147): Server\Asyn\Redis\RedisAsynPool->getSync()
#1 /home/lyl/SwooleDistributed/src/Server/SwooleServer.php(569): Server\SwooleDistributedServer->start()
#2 /home/lyl/SwooleDistributed/src/Server/SwooleServer.php(263): Server\SwooleServer::startSwooles()
#3 /home/lyl/SwooleDistributed/bin/start_swoole_server.php(11): Server\SwooleServer::run()
#4 {main}
  thrown (/home/lyl/SwooleDistributed/src/Server/Asyn/Redis/RedisAsynPool.php:414)
Stack trace:
#0 unknown(0): app\AppServer->checkErrors()

**Comment by 372572571** [comment]
设置了redis 的密码后的错误


`PHP Fatal error:  Uncaught Error: Class 'swoole_redis' not found in /home/lyl/SwooleDistributed/src/Server/Asyn/Redis/RedisAsynPool.php:320
Stack trace:
`

**Comment by 372572571** [comment]
swoole_redis  所以这个类在哪个位子？ 用phpstorm 没搜到

**Comment by 372572571** [comment]
------------- SWOOLE_DISTRIBUTED --------------
System:Linux
SwooleDistributed version:2.0.7
Swoole version: 1.9.8
PHP version: 7.0.18-0ubuntu0.16.04.1
worker_num: 4
task_num: 5
-------------------SERVER----------------------
type        socket      port        status
TCP         0.0.0.0     9093        [OPEN] 
HTTP        0.0.0.0     8081        [OPEN] 
WEBSOCKET   0.0.0.0     8081        [OPEN] 
DISPATCH    0.0.0.0     9991        [OPEN] 
-----------------------------------------------
Press Ctrl-C to quit. Start success.
加载RedisLua脚本=>sadd_from_count
启动了autoReload
[初始化] 清除redis上所有群信息。

 .启动成功。。。是因为swoole编译的时候没有加上async-redis

**Comment by tmtbe** [comment]
可能没法及时反馈，欢迎使用sd框架
