### ISSUE TITLE
你好，请问有未登录也要发送群消息的需求，该怎么做

### ISSUE THREAD

**Issue by yangw1990** [tmtbe/SwooleDistributed#21]
你好，请问有未登录也要发送群消息的需求，该怎么做，测试绑定UID只能正整数，没法区分已登录与未登录用户

**Comment by tmtbe** [comment]
场景描述的再详细点

**Comment by yangw1990** [comment]
addToGroup第一个参数是uid，而需求是有快速登录的用户（即不需要登录）也需要广播（即把group看成是一个房间内的广播），这时候该怎么办呢？

**Comment by tmtbe** [comment]
那只能通过fd发消息了，写个for循环get_instance()->send($this->fd, $data);

**Comment by yangw1990** [comment]
现在遇到一个新的问题，$this->bindUid($this->fd, 50000);
        sleep(2);
        $this->unBindUid(50000);
        sleep(2);
        $this->bindUid($this->fd, 60000);如此后，再进来打印$this->uid，任然为50000，正常应该是60000

**Comment by yangw1990** [comment]
另外，'heartbeat_idle_time' 设置多少，都是2分钟关闭连接
