### ISSUE TITLE
SHOW COLUMNS语句在Task中获取数据的时候返回不正确

### ISSUE THREAD

**Issue by willove** [tmtbe/SwooleDistributed#23]
我扩展了一下模型类，在往数据库插入数据的时候会对字段进行检查，这将会用到 SHOW COLUMNS 语句，但是实际运作中并不能直接获取到 column 数据。

在检查了调用之后发现在 Minert.php 的 coroutineSend 方法里 task 是调用了 pdoQuery($sql) 方法获取数据，而 pdoQuery 方法里仅对 select 语句进行的结果集的获取，不知道是不是因为 show 语句获取的数据比较敏感的原因而没有加上，但是为了我的需求所以我加了下面的语句

```
if ($str == 'select' || strripos($sql, 'show') !== false) {
       $isSelect = true;
}
```
或者可以仅仅对 SHOW COLUMNS 语句进行放行，这个语句用的还挺多的。

**Comment by tmtbe** [comment]
好的了解了，感谢反馈
