### ISSUE TITLE
CPU占用有点高啊

### ISSUE THREAD

**Issue by willove** [tmtbe/SwooleDistributed#24]
![snip20170724_1](https://user-images.githubusercontent.com/5616317/28505371-c7e12046-7055-11e7-89ef-d1645e9a8099.png)

如图，CPU 的占用挺高啊，这算正常么？不用 SD 框架单纯跑 swoole 的话倒是没有这么高，感觉也不像 SD 的版本问题，切到 2.1.0 也是这样。

**Comment by tmtbe** [comment]
首先你应该是mac，其次由于mac没有inotify扩展，是采用轮询的方式判断文件更新进行reload，那么建议你把配置中的auto_reload关闭

**Comment by willove** [comment]
确实关闭了 auto_reload 配置之后那个接近 100% 的进程降下来了。但是占用 9992 端口的 dispatch_udp_port 的 php 进程 CPU 占用还是有些高，这个也是正常的么？

**Comment by tmtbe** [comment]
MAC下CPU占用率确实高，要等swoole适配了，至于linux是正常的，放心
