### ISSUE TITLE
请问mysql的tcp连接会越来越多，我应该在每个model里面调用destroy吗？

### ISSUE THREAD

**Issue by yangw1990** [tmtbe/SwooleDistributed#27]
请问mysql的tcp连接会越来越多，我应该怎么做？

**Comment by yangw1990** [comment]
tcp        0      0 127.0.0.1:47060         127.0.0.1:3306          ESTABLISHED 16411/SWD-Tasker
这种，请解答一下，万分感谢

**Comment by tmtbe** [comment]
Model和Controller都是用连接池的，连接不会变多默认每一个Worker最多10个连接，你这上面是Task,Task是基于PDO的，每个Task理论上只会保留一个PDO连接啊

**Comment by yangw1990** [comment]
可是却是越跑越多，我尝试在task的末尾加上destroy，可还是不断的在增加，最后会提示mysql连接太多

**Comment by tmtbe** [comment]
你最好贴出代码片段，还有对应的SD版本

**Comment by yangw1990** [comment]
我的代码片段就是正常的业务逻辑，有定时器，每5分钟去调用一个model，然后在model里会loader4-5次task，然后就是一些数据库的操作。
每一个task保留一个pdo，是每跑一次task就保留一个pdo吗？不会销毁？

**Comment by tmtbe** [comment]
task进程是固定的，每一个task进程只有一个pdo连接,我需要看下你task调用mysql是怎么写的

**Comment by yangw1990** [comment]
task中：
$room_model = $this->loader->model('roomModel', $this);
        $open_result_model->save(
            [
                'pid' => $pid,
                'gid' => $gid,
                'issue' => $official_lottery['issue'],
                'time' => $official_lottery['time'],
            ]
        );
model中：
public function save($data)
    {
        $this->mysql_pool->dbQueryBuilder
            ->insert("ty_room")
            ->set($data)
            ->coroutineSend();
    }

**Comment by yangw1990** [comment]
task中：
`$open_result_model = $this->loader->model('RoomModel', $this);
        $open_result_model->save(
            [
                'pid' => $pid,
                'gid' => $gid,
                'issue' => $official_lottery['issue'],
                'time' => $official_lottery['time'],
            ]
        );`
model中：
`public function save($data)
    {
        $this->mysql_pool->dbQueryBuilder
            ->insert("ty_rooms")
            ->set($data)
            ->coroutineSend();
    }`

**Comment by tmtbe** [comment]
我刚才压测了下，Model和Task并没有出现mysql连接过多的问题，请问你的SD是什么版本

**Comment by yangw1990** [comment]
System:Linux
SwooleDistributed version:2.0.8
Swoole version: 1.9.18
PHP version: 7.0.22-0ubuntu0.16.04.1

**Comment by tmtbe** [comment]
建议你升级下，如果不想改配置的话，可以升级到2.1.5

**Comment by yangw1990** [comment]
好，那我试试

**Comment by yangw1990** [comment]
我今天重新搭了一个全新的环境，下载了最新版本，然后写了一个测试的task，写了一个定时器每30秒执行一次AppModel，代码如下：
**AppModel:**
class AppModel extends Model
{
    public function test()
    {
        $app_task = $this->loader->task('AppTask');
        $app_task->testTask();
        $app_task->coroutineSend();
    }
}
**AppTask:**
class AppTask extends Task
{
    public function testTask()
    {
        $user_model = $this->loader->model('UserModel', $this);
        $user = $user_model->test();
        print_r($user);
    }
}
**UserModel:**
class UserModel extends Model
{
    public function test()
    {
        $result = $this->mysql_pool->dbQueryBuilder
            ->select("*")
            ->from('ty_users')
            ->coroutineSend()['result'];
        return $result;
    }
}

发现运行的结果是，每30秒执行一次AppModel，都会增加一个SWD-Tasker的tcp进程，端口是3306，也就是连接了数据库

**Comment by tmtbe** [comment]
给下你查看SWD-Tasker的tcp进程的命令

**Comment by yangw1990** [comment]
netstat -apn|grep 3306

**Comment by yangw1990** [comment]
好像和配置的task_worker_num有关，比如配置了5，那么增加到5的时候就停止增加了

**Comment by tmtbe** [comment]
是的啊。。。每个Task会有一个连接，那这样是不是没问题了？

**Comment by yangw1990** [comment]
就算运行同一个task，也是这样吗？

**Comment by tmtbe** [comment]
总之有多少Task就会有Max个PDO连接
