### ISSUE TITLE
websocket分布式错误

### ISSUE THREAD

**Issue by yghcats** [tmtbe/SwooleDistributed#30]
[root@bogon bin]# php start_swoole_dispatch.php start
PHP Fatal error:  Uncaught Error: Class 'Server\SwooleDispatchClient' not found in /home/wwwroot/default/bin/start_swoole_dispatch.php:10
Stack trace:
#0 {main}
  thrown in /home/wwwroot/default/bin/start_swoole_dispatch.php on line 10

这个错误是我安装出问题了吗？

**Comment by tmtbe** [comment]
你好，请更新最新的版本2.4.6,这个SwooleDispatchClient已经被弃用了。在Consul配置中可以开启集群模式，现在不需要SwooleDispatchClient这个中间模块了
