### ISSUE TITLE
route变量全局问题

### ISSUE THREAD

**Issue by jlzan1314** [tmtbe/SwooleDistributed#31]
public function onSwooleRequest($request, $response)
    {
        $error_404 = false;
        $controller_instance = null;
        $this->route->handleClientRequest($request);
        list($host) = explode(':', $request->header['host']??'');
this route 不是每次定义的会不会有并发问题,比如第一个客户端路径是index/test1,另一个客户端,访问一个控制器index/test2,这里的route是同一个,访问量大了会串把? 意思route对象应该跟请求走.

测试了果然有问题,这是全局变量被修改的问题,建议创建route放到onSwooleRequest 中,每个请求一个,用完销毁,
class Index extends Controller
{
	/**
	 * @var ArticleModel
	 */
	public $ArticleModel;

	protected function initialization($controller_name, $method_name)
	{
		parent::initialization($controller_name, $method_name);
		$this->ArticleModel = $this->loader->model('ArticleModel', $this);
	}

    public function http_index()
    {
	    //$this->destroy();
	    $str=get_instance()->route->getMethodName();
	    swoole_timer_after(10000, function()use($str){
		    $this->http_output->end($str."<br/><br/>".get_instance()->route->getMethodName());
	    });
    }

	public function http_test2()
	{
		$this->http_output->end(get_instance()->route->getMethodName());
    }
}

**Comment by tmtbe** [comment]
没有问题的。。你在Controller里就不应该访问Route，initialization的参数已经告诉你了。
