### ISSUE TITLE
Miner JOIN 使用别名后 ON链接条件未使用别名的问题

### ISSUE THREAD

**Issue by nzing** [tmtbe/SwooleDistributed#33]
**报错：**
[mysql]:Unknown column 't_d_order_detail_cmt.order_detail_id' in 'on clause'[sql]:SELECT DISTINCT a.`order_detail_cmt_id`,a.`order_detail_id`,a.`shop_id`,a.`user_id`,a.`order_id`,a.`goods_id`,a.`goods_name`,a.`goods_sku_id`,a.`sku_price_online`,a.`sku_photo`,a.`cmt_content`,a.`cmt_time`,a.`is_anonymous`,a.`reply_content`,a.`reply_time`,a.`order_detail_score`,a.`parent_cmt_id`,a.`create_time`,a.`update_time`,a.`status` FROM t_d_order_detail_cmt AS a INNER JOIN t_d_order_cmt_photo AS b ON t_d_order_detail_cmt.order_detail_id = t_d_order_cmt_photo.order_detail_id WHERE a.shop_id = '1' AND a.goods_id = '1' GROUP BY order_detail_cmt_id ORDER BY order_detail_cmt_id desc LIMIT 0,20

**代码：**
$res = yield $this->read()->dbQueryBuilder->select($this->getFieldStr([], self::TABLE_PK_NAME, 'a'))
                ->from(self::TABLE_NAME, 'a')
                ->innerJoin(self::TABLE_NAME_PHOTO, 'order_detail_id', 'b')
                ->where('a.shop_id', $shopId)
                ->where('a.goods_id', $goodsId)
                ->groupBy('order_detail_cmt_id')
                ->orderBy(self::TABLE_PK_NAME, 'desc')
                ->limit($pages['start'] . ',' . $pageSize)
                ->coroutineSend()->dump();

**Comment by tmtbe** [comment]
Miner的问题，在下一个版本会修复的
