### ISSUE TITLE
miner不支持自写sql字符串

### ISSUE THREAD

**Issue by lixiaohong0212** [tmtbe/SwooleDistributed#36]
版本2.1.5

1.在设置where条件时只支持某个字段或者数组的形式。不支持在已有sql直接拼接一段字符串形成新的sql

例如：
不固定 (status = 1 and dec in ("ss", "cc")) or name = "kk"

2.解决方案
/Server/Asyn/Mysql/Miner.php

/**
     * AND logical operator. 参考laravel起名
     */
 (1)   const LOGICAL_RAW = "RAW";

(2)  方法里的getCriteriaString
从原先的
case self::IS:
case self::IS_NOT:
改成
case self::LOGICAL_RAW:
case self::IS:
case self::IS_NOT:

（3）
在方法里
从原先
         $statement .= $criterion['column'] . " " . $criterion['operator'] . " " . $value;
改成
if ($criterion['operator'] == self::LOGICAL_RAW) {
                    $statement .= " " . $value . " ";
                } else {
                    $statement .= $criterion['column'] . " " . $criterion['operator'] . " " . $value;
                }

3.调用效果支持
$selectMiner = $selectMiner->openWhere();
//wheres 代表 不固定 (status = 1 and dec in ("ss", "cc")) or name = "kk"
$selectMiner = $selectMiner->where('', $wheres, 'RAW');
 $selectMiner = $selectMiner->closeWhere();

**Comment by tmtbe** [comment]
多谢，已采纳

**Comment by tmtbe** [comment]
预计在2.5.2.版本会加入
```
public function http_testMysqlRaw()
    {
        $selectMiner = $this->mysql_pool->dbQueryBuilder->select('*')->from('account');
        $selectMiner = $selectMiner->where('', '(status = 1 and dec in ("ss", "cc")) or name = "kk"', Miner::LOGICAL_RAW);
        $this->http_output->end($selectMiner->getStatement(false));
    }
```
