### ISSUE TITLE
php start_swoole_server.php start 启动报错

### ISSUE THREAD

**Issue by jpyeah** [tmtbe/SwooleDistributed#38]
![image](https://user-images.githubusercontent.com/20105367/31601254-e7d2ba80-b21e-11e7-8fc5-b3f98c410b06.png)

**Comment by jpyeah** [comment]
![image](https://user-images.githubusercontent.com/20105367/31601374-440bf866-b21f-11e7-9c50-8ee86f4958d9.png)

**Comment by jpyeah** [comment]
之前运行还正常，关闭之后在启动就出现了错误

**Comment by tmtbe** [comment]
端口被占用了。你看下是不是有额外的SD进程残留，或者别的服务占用了端口

**Comment by tmtbe** [comment]
或者执行 php start_swoole_server.php kill试一下

**Comment by jpyeah** [comment]
按照你说的执行 php start_swoole_server.php kill 还是不行
然后我又把端口号改成其他的，还是报错，但报错内容改变了
 
![image](https://user-images.githubusercontent.com/20105367/31604965-85dd64fe-b22a-11e7-86f3-75721fb532ad.png)

**Comment by jpyeah** [comment]
已经解决了，重启了一下服务器，进程应该没有彻底杀死
