### ISSUE TITLE
文档与demo是否会继续完善？

### ISSUE THREAD

**Issue by gaoyiping** [tmtbe/SwooleDistributed#46]
文档内功能介绍很全面，示例和demo比较少，SD3.x的文档要25元，价格倒是不贵，但是否物有所值。

**Comment by tmtbe** [comment]
可以看sd2.0的文档,是免费提供的,不过没有整理,   SD3.x的文档一直更新中,demo还没有空去弄,毕竟这是个人项目就我一个人在维护,比较忙
