### ISSUE TITLE
redis_pool sAddArray出错

### ISSUE THREAD

**Issue by GreatSir** [tmtbe/SwooleDistributed#47]
版本3.1.10  swoole版本2.1.2
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Array to string conversion in /data/sd/vendor/tmtbe/swooledistributed/src/Server/Asyn/Redis/RedisAsynPool.php:359
Stack trace:
#0 [internal function]: Server\SwooleServer->displayErrorHandler(8, 'Array to string...', '/data/sd/vendor...', 359, Array)
#1 /data/sd/vendor/tmtbe/swooledistributed/src/Server/Asyn/Redis/RedisAsynPool.php(359): Swoole\Redis->__call('sAddArray', Array)
#2 /data/sd/vendor/tmtbe/swooledistributed/src/Server/Asyn/AsynPool.php(157): Server\Asyn\Redis\RedisAsynPool->execute(Array)
#3 /data/sd/vendor/tmtbe/swooledistributed/src/Server/Asyn/Redis/RedisAsynPool.php(389): Server\Asyn\AsynPool->pushToPool(Object(Swoole\Redis))
#4 [internal function]: Server\Asyn\Redis\RedisAsynPool->Server\Asyn\Redis\{closure}(Object(Swoole\Redis), 'OK')
#5 /data/sd/vendor/tmtbe/swooledistributed/src/Server/Coroutine/CoroutineBase.php(131): Swoole\Coroutine\Channel::select(Array, NULL, 5)
#6 /data/sd/vendor/tmtbe/swooledistributed/src/Server/Coroutine/CoroutineBase.php in /data/sd/vendor/tmtbe/swooledistributed/src/Server/Asyn/Redis/RedisAsynPool.php on line 359

**Comment by tmtbe** [comment]
好的，新版本已修复了吧

**Comment by tmtbe** [comment]
看了下redis并没有sAddArray这个命令，直接用sAdd
