### ISSUE TITLE
PHP 7.2 版本不兼容

### ISSUE THREAD

**Issue by yann0917** [tmtbe/SwooleDistributed#53]
* sd version: 3.2.6
* PHP version：7.2.7
* error info
```
Fatal error: Uncaught Whoops\Exception\ErrorException: count(): Parameter must be an array or an object that implements Countable in /wwwroot/netbar/vendor/tmtbe/swooledistributed/src/Server/SwooleDistributedServer.php:774
```

* root cause
> Document[function.count](https://secure.php.net/manual/en/function.count.php)

|Version| Description|
|---|---|
|7.2.0 | `count()` will now yield a warning on invalid countable types passed to the `array_or_countable` parameter.|

**Comment by tmtbe** [comment]
能把774行的代码贴一下么

**Comment by tmtbe** [comment]
应该是swoole扩展的兼容问题，我下个版本会修复

**Comment by yann0917** [comment]
```php
public function unBindUid($uid, $fd)
{
        //更新共享内存
        $this->uid_fd_table->del($uid);
        $this->fd_uid_table->del($fd);
        //这里无论是不是集群都需要调用
        ProcessManager::getInstance()->getRpcCall(ClusterProcess::class, true)->my_removeUid($uid);
        if (!$this->isCluster()) {
            get_instance()->pub('$SYS/uidcount', count($this->uid_fd_table));
        }
}
```
line 774:`get_instance()->pub('$SYS/uidcount', count($this->uid_fd_table));`

**Comment by tmtbe** [comment]
嗯，那就是swoole扩展table和7.2版本的php兼容问题了，count($this->uid_fd_table)会报错，你可以先修改为$this->uid_fd_table->count();我向swoole那边反馈。
