### ISSUE TITLE
不支持Swoole4.2.5

### ISSUE THREAD

**Issue by weijer** [tmtbe/SwooleDistributed#64]
报错信息
![_20181030212756](https://user-images.githubusercontent.com/12838756/47721260-b11f0d80-dc8a-11e8-9eb8-37e91b4ae2fd.png)

**Comment by loyating** [comment]
都没有建立connect 直接close了

**Comment by weijer** [comment]
> 都没有建立connect 直接close了

这是框架处理的~

**Comment by weijer** [comment]
端口占用问题~ 不是框架问题！close
