### ISSUE TITLE
非常好的项目，适合做微服务

### ISSUE THREAD

**Issue by kcloze** [tmtbe/SwooleDistributed#8]
1.跟微服务的概念很像，从性能来看很适合做微服务，没明白dispatch的作用，可借借鉴服务发现和注册
2.代码分割不是很统一，下横杆的命名跟驼峰并存，建议符合psr1,psr2和psr4规范
    psr:  https://psr.phphub.org/

**Comment by tmtbe** [comment]
谢谢支持sd会慢慢变得更加优秀
